### ISSUE TITLE
Tested (no longer with Kotlin BT) SBF77 setups with V3 beta (v3)

### ISSUE THREAD

**Issue by bsimmo** [oliexdev/openScale#1169]
I thought it might be useful for people to list actual working setups with the v3 beta.
Just so you know :-)

Build : Using 3.0 beta build 30 August 25 (68)

Scale : Silvercrest SBF77
Android Version : 15  (1st May 25 security)
Device : Moto Edge 50 Pro

Can get users, connect and get data.
Tried a few times now.

will check in more detail if it all looks correct.

**Comment by oliexdev** [comment]
Thanks but could you test the [latest beta build ](https://github.com/oliexdev/openScale/releases/tag/beta-build) again? 
I’ve migrated the old Java scale handler to the modern Kotlin handler.

**Comment by bsimmo** [comment]
Current beta says the scale is not supported :-(
(Restoration of data works though).



There is a bug in the older V3 version
When the scale syncs on kg (which I guess SBF77 does), OpenScale takes that as the reading and doesn't convert it to the selected measurement as selected for showing.
(I do have a screenshot)

Previous reading where all when set to kg, then changed it to display stone, last one was a resync.
Will test with current new version once it is compatible.

**Comment by oliexdev** [comment]
Thanks for your feedback I have fixed your two hints in the latest build, lets see if you can connect to your scale.

**Comment by bsimmo** [comment]
Will have a look at the other stuff, 
Build yesterday could see the scale. But I did have the app crash out with connections.
Oddly as soon as I enabled debug onto the BT connection it wouldn't crash of course!

**Comment by oliexdev** [comment]
please post the log file without one I sticking in the dark.

**Comment by bsimmo** [comment]
using today build (doesn't crash)
Broken BT, did a clean BT connection to connect. (Phone)

New user etc
Just sits there. Maybe eventually saying stand on scale , it should go to select user and then enter consent/pin code. It never had stand on scale before.
Working before the new BT stack (Kotlin)

 Field | Value |
|---|---|
| Time | 2025-09-22 21:21:09.138 |
| Session ID | 19973165b92 |
| App | openScale |
| Version | 3.0-beta (68) |
| Package | com.health.openscale.beta |
| Build Type | beta |
| Device | motorola motorola edge 50 pro |
| Android | 15 (API 35) |
| Build ID | V1UMS35H.10-67-7-2 |
| Build Time | 2025-09-22T15:30:22Z |
| Git SHA | ef75860 |

```diff
+ 2025-09-22 21:21:09.135 I/openScaleLog: File logging preference updated to: true (was: false)
? 2025-09-22 21:21:09.139 D/openScaleLog: Initial markdown-diff headers written to: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs/openScale_current_log.txt
+ 2025-09-22 21:21:09.139 I/openScaleLog: File logging enabled during runtime – started fresh session log.
+ 2025-09-22 21:21:19.126 I/UserSettingsRepository: Saving device snapshot: addr=SBF77, name=Debug, uuids=0, hint=Debug
+ 2025-09-22 21:21:28.991 I/BluetoothConnManager: Attempting to connect to Debug
? 2025-09-22 21:21:28.992 D/BluetoothConnManager: Switching to new device: Releasing active communicator: null
? 2025-09-22 21:21:28.993 D/BluetoothConnManager: Switching to new device: Active communicator released and set to null.
? 2025-09-22 21:21:28.994 D/ScaleHandlerFactory: createCommunicator: Searching for communicator for 'Debug' (SBF77). Handler hint: 'Debug'
+ 2025-09-22 21:21:28.997 I/ScaleHandlerFactory: Modern handler 'Debug' supports 'Debug'.
+ 2025-09-22 21:21:28.999 I/ScaleHandlerFactory: Modern communicator 'GattScaleAdapter' created for 'Debug'.
+ 2025-09-22 21:21:28.999 I/BluetoothConnManager: ActiveCommunicator successfully created: GattScaleAdapter. Starting observation job...
? 2025-09-22 21:21:29.000 D/BluetoothConnManager: Adapter isConnected: false for Debug (Status: CONNECTING)
+ 2025-09-22 21:21:29.000 I/BluetoothConnManager: Adapter no longer reports connected for Debug. Current status: CONNECTING. Expecting Disconnected Event.

```

**Comment by bsimmo** [comment]
Just tested with latest beta build.
Still no luck getting it to work, same problem


anything else you need ?

_Recap (for me)_
It was working in V3 beta before that update to Kotlin
 The first update it couldn't find the SBF device .
_You fixed that :-)_
Then it was crashing when it could see it.
_That seems to be fixed. :-)_
Now it can see it but doesn't sync, get users or update (even if I use a backup to try help it).

I do get a message to step on the scale (that's new and was never needed) but it does nothing.

I have relinked BT by resetting it.

**Comment by oliexdev** [comment]
please post always the log file

**Comment by bsimmo** [comment]
It's still not working, I tested yesterday, still works with V2 and the older pre rewrite V3.

Is that not he log file above.
I can do a new one if  you need anything more specific.

(Sorry for the delay getting back)

**Comment by bsimmo** [comment]
| Field | Value |
|---|---|
| Time | 2025-10-18 13:03:54.566 |
| Session ID | 199f7347646 |
| App | openScale |
| Version | 3.0-beta (69) |
| Package | com.health.openscale.beta |
| Build Type | beta |
| Device | motorola motorola edge 50 pro |
| Android | 15 (API 35) |
| Build ID | V1UMS35H.10-67-7-2 |
| Build Time | 2025-10-18T10:25:37Z |
| Git SHA | c85de04 |

```diff
? 2025-10-18 13:03:54.566 D/openScaleLog: Initial markdown-diff headers written to: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs/openScale_current_log.txt
? 2025-10-18 13:03:54.567 D/openScaleLog: Initial markdown-diff headers written to: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs/openScale_current_log.txt
+ 2025-10-18 13:03:54.567 I/openScaleLog: File logging enabled during runtime – started fresh session log.
? 2025-10-18 13:04:02.402 D/BluetoothTopBar: User clicked bluetooth icon connect → trying to connect to saved device Debug
+ 2025-10-18 13:04:02.405 I/BleConnector: Attempting to connect to Debug
? 2025-10-18 13:04:02.406 D/BleConnector: Switching to new device: Releasing active communicator: null
? 2025-10-18 13:04:02.407 D/BleConnector: Switching to new device: Active communicator released and set to null.
? 2025-10-18 13:04:02.408 D/ScaleHandlerFactory: createCommunicator: Searching for communicator for 'Debug' (C7:34:11:85:8F:E0). Handler hint: 'Debug'
+ 2025-10-18 13:04:02.410 I/ScaleHandlerFactory: Modern handler 'Debug' supports 'Debug'.
+ 2025-10-18 13:04:02.415 I/ScaleHandlerFactory: Modern communicator 'GattScaleAdapter' created for 'Debug' with linkMode=CONNECT_GATT.
+ 2025-10-18 13:04:02.415 I/BleConnector: ActiveCommunicator successfully created: GattScaleAdapter. Starting observation job...
? 2025-10-18 13:04:02.417 D/BleConnector: Adapter isConnected: false for Debug (Status: CONNECTING)
+ 2025-10-18 13:04:02.418 I/BleConnector: Adapter no longer reports connected for Debug. Current status: CONNECTING. Expecting Disconnected Event.
+ 2025-10-18 13:04:10.353 I/GattScaleAdapter: Found C7:34:11:85:8F:E0 → stop scan + connect
? 2025-10-18 13:04:23.447 D/GattScaleAdapter: Services discovered for C7:34:11:85:8F:E0
? 2025-10-18 13:04:23.450 D/DebugGattHandler: attach()
? 2025-10-18 13:04:23.451 D/DebugGattHandler: handleConnected(userId=1, height=170.0, age=18)
? 2025-10-18 13:04:23.452 D/DebugGattHandler: Connected in Debug mode. Dumping full GATT services/characteristics…
? 2025-10-18 13:04:23.453 D/DebugGattHandler: === GATT Service Dump BEGIN ===
? 2025-10-18 13:04:23.454 D/DebugGattHandler: Service 0x1800
? 2025-10-18 13:04:23.455 D/DebugGattHandler:   └─ Char 0x2a00 props=READ
? 2025-10-18 13:04:23.456 D/DebugGattHandler:   └─ Char 0x2a01 props=READ
? 2025-10-18 13:04:23.457 D/DebugGattHandler:   └─ Char 0x2a02 props=READ|WRITE
? 2025-10-18 13:04:23.457 D/DebugGattHandler:   └─ Char 0x2a03 props=WRITE
? 2025-10-18 13:04:23.458 D/DebugGattHandler:   └─ Char 0x2a04 props=READ
? 2025-10-18 13:04:23.459 D/DebugGattHandler: Service 0x1801
? 2025-10-18 13:04:23.460 D/DebugGattHandler:   └─ Char 0x2a05 props=INDICATE
? 2025-10-18 13:04:23.461 D/DebugGattHandler: Service 0x180a
? 2025-10-18 13:04:23.462 D/DebugGattHandler:   └─ Char 0x2a24 props=READ
? 2025-10-18 13:04:23.463 D/DebugGattHandler:   └─ Char 0x2a26 props=READ
? 2025-10-18 13:04:23.464 D/DebugGattHandler:   └─ Char 0x2a27 props=READ
? 2025-10-18 13:04:23.465 D/DebugGattHandler:   └─ Char 0x2a28 props=READ
? 2025-10-18 13:04:23.466 D/DebugGattHandler:   └─ Char 0x2a29 props=READ
? 2025-10-18 13:04:23.466 D/DebugGattHandler: Service 0x180f
? 2025-10-18 13:04:23.466 D/DebugGattHandler:   └─ Char 0x2a2a props=READ
? 2025-10-18 13:04:23.467 D/DebugGattHandler:   └─ Char 0x2a19 props=READ
? 2025-10-18 13:04:23.467 D/DebugGattHandler: Service 0x1805
? 2025-10-18 13:04:23.467 D/DebugGattHandler:   └─ Char 0x2a2b props=READ|WRITE|NOTIFY
? 2025-10-18 13:04:23.468 D/DebugGattHandler: Service 0x181c
? 2025-10-18 13:04:23.468 D/DebugGattHandler:   └─ Char 0x2a85 props=READ|WRITE
? 2025-10-18 13:04:23.468 D/DebugGattHandler:   └─ Char 0x2a8c props=READ|WRITE
? 2025-10-18 13:04:23.469 D/DebugGattHandler:   └─ Char 0x2a99 props=READ|WRITE|NOTIFY
? 2025-10-18 13:04:23.469 D/DebugGattHandler:   └─ Char 0x2a9a props=READ
? 2025-10-18 13:04:23.470 D/DebugGattHandler:   └─ Char 0x2a9f props=WRITE|INDICATE
? 2025-10-18 13:04:23.470 D/DebugGattHandler: Service 0x181d
? 2025-10-18 13:04:23.470 D/DebugGattHandler:   └─ Char 0x2a9e props=READ
? 2025-10-18 13:04:23.470 D/DebugGattHandler:   └─ Char 0x2a9d props=INDICATE
? 2025-10-18 13:04:23.471 D/DebugGattHandler: Service 0x181b
? 2025-10-18 13:04:23.471 D/DebugGattHandler:   └─ Char 0x2a9b props=READ
? 2025-10-18 13:04:23.471 D/DebugGattHandler:   └─ Char 0x2a9c props=INDICATE
? 2025-10-18 13:04:23.471 D/DebugGattHandler: Service 0xffff
? 2025-10-18 13:04:23.472 D/DebugGattHandler:   └─ Char 0x0000 props=READ|WRITE
? 2025-10-18 13:04:23.469 D/DebugGattHandler:   └─ Char 0x2a8e props=READ|WRITE
? 2025-10-18 13:04:23.472 D/DebugGattHandler:   └─ Char 0x0001 props=READ|WRITE|NOTIFY
? 2025-10-18 13:04:23.472 D/DebugGattHandler:   └─ Char 0x0002 props=READ|WRITE
? 2025-10-18 13:04:23.472 D/DebugGattHandler:   └─ Char 0x0004 props=READ|WRITE
? 2025-10-18 13:04:23.473 D/DebugGattHandler:   └─ Char 0x000b props=READ
? 2025-10-18 13:04:23.473 D/DebugGattHandler:   └─ Char 0x0005 props=READ|WRITE
? 2025-10-18 13:04:23.473 D/DebugGattHandler:   └─ Char 0x0006 props=READ|WRITE|NOTIFY
? 2025-10-18 13:04:23.473 D/DebugGattHandler: Service 0xff00
? 2025-10-18 13:04:23.474 D/DebugGattHandler:   └─ Char 0xff01 props=READ|WRITE|WRITE_NR
? 2025-10-18 13:04:23.474 D/DebugGattHandler: === GATT Service Dump END ===
? 2025-10-18 13:04:23.474 D/DebugGattHandler: → read svc=0x1800 chr=0x2a00 (best effort)
? 2025-10-18 13:04:23.475 D/GattScaleAdapter: → read from chr=00002a00-0000-1000-8000-00805f9b34fb svc=00001800-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:23.475 D/DebugGattHandler: → read svc=0x180a chr=0x2a24 (best effort)
? 2025-10-18 13:04:23.475 D/DebugGattHandler: → read svc=0x180a chr=0x2a26 (best effort)
? 2025-10-18 13:04:23.475 D/DebugGattHandler: → read svc=0x180a chr=0x2a29 (best effort)
? 2025-10-18 13:04:23.476 D/DebugGattHandler: → read svc=0x180a chr=0x2a28 (best effort)
? 2025-10-18 13:04:23.476 D/DebugGattHandler: → read svc=0x180f chr=0x2a19 (best effort)
? 2025-10-18 13:04:23.477 D/DebugGattHandler: → setNotifyOn svc=0x181d chr=0x2a9d
? 2025-10-18 13:04:23.477 D/DebugGattHandler: → setNotifyOn svc=0x181b chr=0x2a9c
? 2025-10-18 13:04:23.477 D/DebugGattHandler: Debug handler armed. Incoming NOTIFY frames will be logged; no data is stored.
? 2025-10-18 13:04:23.478 D/BleConnector: Adapter isConnected: true for Debug (Status: CONNECTING)
+ 2025-10-18 13:04:23.478 I/BleConnector: Successfully connected to Debug via adapter's isConnected flow.
? 2025-10-18 13:04:23.484 D/BleConnector: BluetoothEvent received: Connected(deviceName=SBF77, deviceAddress=C7:34:11:85:8F:E0) for Debug
+ 2025-10-18 13:04:23.484 I/BleConnector: Event: Connected to SBF77 (C7:34:11:85:8F:E0)
? 2025-10-18 13:04:24.148 D/GattScaleAdapter: ← received data chr=00002a00-0000-1000-8000-00805f9b34fb len=5 status=SUCCESS payload=[53 42 46 37 37]
? 2025-10-18 13:04:24.149 D/DebugGattHandler: NOTIFY chr=0x2a00  payload=[53 42 46 37 37]  ascii=SBF77
? 2025-10-18 13:04:24.172 D/GattScaleAdapter: → read from chr=00002a29-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:24.240 D/GattScaleAdapter: ← received data chr=00002a29-0000-1000-8000-00805f9b34fb len=13 status=SUCCESS payload=[48 61 6E 73 20 44 69 6E 73 6C 61 67 65]
? 2025-10-18 13:04:24.245 D/DebugGattHandler: NOTIFY chr=0x2a29  payload=[48 61 6E 73 20 44 69 6E 73 6C 61 67 65]  ascii=Hans Dinslage
? 2025-10-18 13:04:24.269 D/GattScaleAdapter: → read from chr=00002a24-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:24.342 D/GattScaleAdapter: ← received data chr=00002a24-0000-1000-8000-00805f9b34fb len=5 status=SUCCESS payload=[53 42 46 37 37]
? 2025-10-18 13:04:24.343 D/DebugGattHandler: NOTIFY chr=0x2a24  payload=[53 42 46 37 37]  ascii=SBF77
? 2025-10-18 13:04:24.368 D/GattScaleAdapter: → read from chr=00002a26-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:24.432 D/GattScaleAdapter: ← received data chr=00002a26-0000-1000-8000-00805f9b34fb len=3 status=SUCCESS payload=[37 2E 38]
? 2025-10-18 13:04:24.433 D/DebugGattHandler: NOTIFY chr=0x2a26  payload=[37 2E 38]  ascii=7.8
? 2025-10-18 13:04:24.457 D/GattScaleAdapter: → read from chr=00002a28-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:24.522 D/GattScaleAdapter: ← received data chr=00002a28-0000-1000-8000-00805f9b34fb len=3 status=SUCCESS payload=[35 2E 37]
? 2025-10-18 13:04:24.523 D/DebugGattHandler: NOTIFY chr=0x2a28  payload=[35 2E 37]  ascii=5.7
? 2025-10-18 13:04:24.546 D/GattScaleAdapter: → read from chr=00002a19-0000-1000-8000-00805f9b34fb svc=0000180f-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:24.613 D/GattScaleAdapter: ← received data chr=00002a19-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[5C]
? 2025-10-18 13:04:24.614 D/DebugGattHandler: NOTIFY chr=0x2a19  payload=[5C]  ascii=\
? 2025-10-18 13:04:24.636 D/GattScaleAdapter: → set notify on chr=00002a9d-0000-1000-8000-00805f9b34fb svc=0000181d-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:24.702 D/GattScaleAdapter: ← notify state chr=00002a9d-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 13:04:24.825 D/GattScaleAdapter: → set notify on chr=00002a9c-0000-1000-8000-00805f9b34fb svc=0000181b-0000-1000-8000-00805f9b34fb
? 2025-10-18 13:04:24.869 D/GattScaleAdapter: ← notify state chr=00002a9c-0000-1000-8000-00805f9b34fb status=SUCCESS
+ 2025-10-18 13:05:00.426 I/BleConnector: disconnect() called for Debug. Active communicator: true, Status: CONNECTED
? 2025-10-18 13:05:00.427 D/BleConnector: Adapter isConnected: false for Debug (Status: DISCONNECTING)
+ 2025-10-18 13:05:00.428 I/BleConnector: Adapter no longer reports connected for Debug. Current status: DISCONNECTING. Expecting Disconnected Event.
+ 2025-10-18 13:05:00.455 I/GattScaleAdapter: Disconnected C7:34:11:85:8F:E0: SUCCESS
? 2025-10-18 13:05:00.455 D/DebugGattHandler: handleDisconnected()
? 2025-10-18 13:05:00.456 D/DebugGattHandler: detach()
? 2025-10-18 13:05:00.456 D/BleConnector: BluetoothEvent received: Disconnected(deviceAddress=C7:34:11:85:8F:E0, reason=SUCCESS) for Debug
+ 2025-10-18 13:05:00.457 I/BleConnector: Event: Disconnected from C7:34:11:85:8F:E0. Reason: SUCCESS
? 2025-10-18 13:05:00.458 D/BleConnector: Disconnected event: Releasing active communicator: GattScaleAdapter
? 2025-10-18 13:05:00.458 D/BleConnector: Disconnected event: Active communicator released and set to null.

```
With today's new build.

**Comment by oliexdev** [comment]
you have enabled the debug mode!? I show extra a warning when you enabling it, I guess nobody reads that nor reading the log file...

**Comment by bsimmo** [comment]
I enabled the Bluetooth as debug, enabled the log file creation in setting, went through the process of connecting etc, waiting some time, saved it. Then copy pasted the log here. Twice now. Which you nicely formatted to make it easy to read.
Which is what the V3 beta invite thread says iirc.

**Comment by bsimmo** [comment]
I.E

<img width="1220" height="2712" alt="Image" src="https://github.com/user-attachments/assets/cb45b05a-786c-4461-86ef-8757b4c43a01" />
<img width="1220" height="2712" alt="Image" src="https://github.com/user-attachments/assets/fe8bd670-c64c-455e-8f42-0e6af25d247d" />

**Comment by oliexdev** [comment]
Please read that:

<img width="1812" height="498" alt="Image" src="https://github.com/user-attachments/assets/2050d661-ec63-48ad-83d6-b8a1a8e3c85d" />

You have to remove the debug device and search for the scale again and select that without going into the Bluetooth debug mode. I thought I have clearly written everywhere that this for debugging, I guess not...

**Comment by bsimmo** [comment]
Yes I read that and hence I have provided the debug logs (twice) to try and
fix the problem.
You don't need my weight and stays data (which is what it is not recording, but it doesn't get that far anyway).

Are we not debugging why it is not working properly and it does not talk to
and get data from the SBF77 anymore.


I'll grab the logs with debugging *disabled*.

**Comment by bsimmo** [comment]
So here is the log without debugging enabled.

As I said, it scans and finds the device.
It then asks you to stand on it (this is a new feature).
It then does nothing, it does not ask for consent like before about users.  This broke as mentioned before with the Kotlin BT update.


| Field | Value |
|---|---|
| Time | 2025-10-18 15:16:36.880 |
| Session ID | 199f7adf512 |
| App | openScale |
| Version | 3.0-beta (69) |
| Package | com.health.openscale.beta |
| Build Type | beta |
| Device | motorola motorola edge 50 pro |
| Android | 15 (API 35) |
| Build ID | V1UMS35H.10-67-7-2 |
| Build Time | 2025-10-18T10:25:37Z |
| Git SHA | c85de04 |

```diff
? 2025-10-18 15:16:36.872 D/OpenScaleApp: Checking for first app start. isFirstAppStart: false
+ 2025-10-18 15:16:36.872 I/OpenScaleApp: LogManager initialized. File logging enabled: true
+ 2025-10-18 15:16:36.873 I/DatabaseProvider: DatabaseProvider initialized with file logging = true
? 2025-10-18 15:16:36.877 D/openScaleLog: Previous log file deleted on startup: openScale_current_log.txt
? 2025-10-18 15:16:36.878 D/OpenScaleApp: Not the first app start. Default data should already exist.
? 2025-10-18 15:16:36.881 D/openScaleLog: Initial markdown-diff headers written to: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs/openScale_current_log.txt
? 2025-10-18 15:16:36.882 D/openScaleLog: Initial markdown-diff headers written to: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs/openScale_current_log.txt
+ 2025-10-18 15:16:36.885 I/openScaleLog: LogManager initialized. Logging to file: enabled. Log directory: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs
? 2025-10-18 15:16:36.964 D/MainActivity: Observed language code: null, Current activity locale: en, Target: en
? 2025-10-18 15:16:36.965 D/MainActivity: Initializing and setting content.
+ 2025-10-18 15:16:37.684 I/BluetoothFacade: User context updated -> Ben
? 2025-10-18 15:16:37.741 D/SharedViewModel: Backfill skip: no measurements for userId=1.
+ 2025-10-18 15:16:37.741 I/SharedViewModel: Derived backfill not needed for any user.
? 2025-10-18 15:16:42.416 D/BluetoothTopBar: User clicked bluetooth icon connect → trying to connect to saved device SBF77
+ 2025-10-18 15:16:42.419 I/BleConnector: Attempting to connect to SBF77
? 2025-10-18 15:16:42.419 D/BleConnector: Switching to new device: Releasing active communicator: null
? 2025-10-18 15:16:42.419 D/BleConnector: Switching to new device: Active communicator released and set to null.
? 2025-10-18 15:16:42.420 D/ScaleHandlerFactory: createCommunicator: Searching for communicator for 'SBF77' (C7:34:11:85:8F:E0). Handler hint: 'Beurer BF950'
+ 2025-10-18 15:16:42.420 I/ScaleHandlerFactory: Modern handler 'Beurer BF950' supports 'SBF77'.
+ 2025-10-18 15:16:42.425 I/ScaleHandlerFactory: Modern communicator 'GattScaleAdapter' created for 'SBF77' with linkMode=CONNECT_GATT.
+ 2025-10-18 15:16:42.426 I/BleConnector: ActiveCommunicator successfully created: GattScaleAdapter. Starting observation job...
? 2025-10-18 15:16:42.427 D/BleConnector: Adapter isConnected: false for SBF77 (Status: CONNECTING)
+ 2025-10-18 15:16:42.428 I/BleConnector: Adapter no longer reports connected for SBF77. Current status: CONNECTING. Expecting Disconnected Event.
+ 2025-10-18 15:16:49.631 I/GattScaleAdapter: Found C7:34:11:85:8F:E0 → stop scan + connect
? 2025-10-18 15:16:54.857 D/GattScaleAdapter: Services discovered for C7:34:11:85:8F:E0
? 2025-10-18 15:16:54.858 D/StandardBeurerSanitasHandler: attach()
? 2025-10-18 15:16:54.859 D/StandardBeurerSanitasHandler: handleConnected(userId=1, height=170.0, age=18)
? 2025-10-18 15:16:54.860 D/StandardBeurerSanitasHandler: tryAutoConsent called for appUserId=1
? 2025-10-18 15:16:54.860 D/GattScaleAdapter: → set notify on chr=00002a9d-0000-1000-8000-00805f9b34fb svc=0000181d-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:54.956 D/StandardBeurerSanitasHandler: No known scale index found for appUserId=1, auto-consent cannot proceed
? 2025-10-18 15:16:54.956 D/StandardBeurerSanitasHandler: → UCP LIST_ALL_USERS
? 2025-10-18 15:16:54.957 D/StandardBeurerSanitasHandler: Scale connected: userId=1, name=Ben
? 2025-10-18 15:16:54.957 D/StandardBeurerSanitasHandler: Setting notifications on service=0000ffff-0000-1000-8000-00805f9b34fb for chrUserList=00000001-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:54.958 D/StandardBeurerSanitasHandler: Writing activity level for userId=1 to chrActivity=00000004-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:54.958 D/StandardBeurerSanitasHandler: Writing initials for userId=1 to chrInitials=00000002-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:54.959 D/BleConnector: Adapter isConnected: true for SBF77 (Status: CONNECTING)
+ 2025-10-18 15:16:54.960 I/BleConnector: Successfully connected to SBF77 via adapter's isConnected flow.
? 2025-10-18 15:16:54.962 D/BleConnector: BluetoothEvent received: Connected(deviceName=SBF77, deviceAddress=C7:34:11:85:8F:E0) for SBF77
+ 2025-10-18 15:16:54.962 I/BleConnector: Event: Connected to SBF77 (C7:34:11:85:8F:E0)
? 2025-10-18 15:16:54.963 D/BleConnector: BluetoothEvent received: DeviceMessage(message=Please step barefoot on the scale, deviceAddress=C7:34:11:85:8F:E0) for SBF77
? 2025-10-18 15:16:54.963 D/BleConnector: Event: Message from SBF77: Please step barefoot on the scale
? 2025-10-18 15:16:55.539 D/GattScaleAdapter: ← notify state chr=00002a9d-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 15:16:55.664 D/GattScaleAdapter: → set notify on chr=00002a9c-0000-1000-8000-00805f9b34fb svc=0000181b-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:55.718 D/GattScaleAdapter: ← notify state chr=00002a9c-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 15:16:55.846 D/GattScaleAdapter: → set notify on chr=00002a99-0000-1000-8000-00805f9b34fb svc=0000181c-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:55.883 D/GattScaleAdapter: ← notify state chr=00002a99-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 15:16:56.011 D/GattScaleAdapter: → set notify on chr=00002a9f-0000-1000-8000-00805f9b34fb svc=0000181c-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:56.064 D/GattScaleAdapter: ← notify state chr=00002a9f-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 15:16:56.192 D/GattScaleAdapter: → set notify on chr=00002a19-0000-1000-8000-00805f9b34fb svc=0000180f-0000-1000-8000-00805f9b34fb
- 2025-10-18 15:16:56.198 E/GattScaleAdapter: BLE operation failed
java.lang.IllegalArgumentException: could not get CCC descriptor for characteristic 00002a19-0000-1000-8000-00805f9b34fb
	at com.welie.blessed.BluetoothPeripheral.setNotify(BluetoothPeripheral.kt:1138)
	at com.welie.blessed.BluetoothPeripheral.setNotify(BluetoothPeripheral.kt:1119)
	at com.welie.blessed.BluetoothPeripheral.startNotify(BluetoothPeripheral.kt:1093)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$transport$1$setNotifyOn$1.invokeSuspend(GattScaleAdapter.kt:237)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$transport$1$setNotifyOn$1.invoke(Unknown Source:8)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$transport$1$setNotifyOn$1.invoke(Unknown Source:2)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$1.invokeSuspend(GattScaleAdapter.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)

? 2025-10-18 15:16:56.288 D/GattScaleAdapter: → write to chr=00002a2b-0000-1000-8000-00805f9b34fb svc=00001805-0000-1000-8000-00805f9b34fb len=10 withResp=true payload=[E9 07 0A 12 0F 10 36 06 00 00]
? 2025-10-18 15:16:56.319 D/GattScaleAdapter: ← write response chr=00002a2b-0000-1000-8000-00805f9b34fb len=10 status=SUCCESS payload=[E9 07 0A 12 0F 10 36 06 00 00]
? 2025-10-18 15:16:56.344 D/GattScaleAdapter: → read from chr=00002a29-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:56.396 D/GattScaleAdapter: ← received data chr=00002a29-0000-1000-8000-00805f9b34fb len=13 status=SUCCESS payload=[48 61 6E 73 20 44 69 6E 73 6C 61 67 65]
? 2025-10-18 15:16:56.399 D/StandardBeurerSanitasHandler: Device info: Hans Dinslage
? 2025-10-18 15:16:56.426 D/GattScaleAdapter: → read from chr=00002a24-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:56.454 D/GattScaleAdapter: ← received data chr=00002a24-0000-1000-8000-00805f9b34fb len=5 status=SUCCESS payload=[53 42 46 37 37]
? 2025-10-18 15:16:56.455 D/StandardBeurerSanitasHandler: Device info: SBF77
? 2025-10-18 15:16:56.479 D/GattScaleAdapter: → read from chr=00002a19-0000-1000-8000-00805f9b34fb svc=0000180f-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:56.512 D/GattScaleAdapter: ← received data chr=00002a19-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[5A]
? 2025-10-18 15:16:56.513 D/StandardBeurerSanitasHandler: Battery level: 90%
? 2025-10-18 15:16:56.622 D/GattScaleAdapter: → write to chr=00002a9f-0000-1000-8000-00805f9b34fb svc=0000181c-0000-1000-8000-00805f9b34fb len=1 withResp=true payload=[04]
? 2025-10-18 15:16:56.647 D/GattScaleAdapter: ← write response chr=00002a9f-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[04]
? 2025-10-18 15:16:56.671 D/GattScaleAdapter: → set notify on chr=00000001-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb
? 2025-10-18 15:16:56.737 D/GattScaleAdapter: ← notify state chr=00000001-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 15:16:56.944 D/GattScaleAdapter: → write to chr=00000004-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb len=1 withResp=true payload=[01]
? 2025-10-18 15:16:56.976 D/GattScaleAdapter: ← write response chr=00000004-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[01]
? 2025-10-18 15:16:57.082 D/GattScaleAdapter: → write to chr=00000002-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb len=3 withResp=true payload=[42 45 4E]
? 2025-10-18 15:16:57.113 D/GattScaleAdapter: ← write response chr=00000002-0000-1000-8000-00805f9b34fb len=3 status=SUCCESS payload=[42 45 4E]

```
000-00805f9b34fb len=1 withResp=true payload=[01]
? 2025-10-18 15:11:37.015 D/GattScaleAdapter: ← write response chr=00000004-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[01]
? 2025-10-18 15:11:37.125 D/GattScaleAdapter: → write to chr=00000002-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb len=3 withResp=true payload=[42 45 4E]
? 2025-10-18 15:11:37.149 D/GattScaleAdapter: ← write response chr=00000002-0000-1000-8000-00805f9b34fb len=3 status=SUCCESS payload=[42 45 4E]
+ 2025-10-18 15:12:06.592 I/BleConnector: disconnect() called for SBF77. Active communicator: true, Status: CONNECTED
? 2025-10-18 15:12:06.593 D/BleConnector: Adapter isConnected: false for SBF77 (Status: DISCONNECTING)
+ 2025-10-18 15:12:06.593 I/BleConnector: Adapter no longer reports connected for SBF77. Current status: DISCONNECTING. Expecting Disconnected Event.
+ 2025-10-18 15:12:06.610 I/GattScaleAdapter: Disconnected C7:34:11:85:8F:E0: SUCCESS
? 2025-10-18 15:12:06.612 D/StandardBeurerSanitasHandler: handleDisconnected()
? 2025-10-18 15:12:06.613 D/StandardBeurerSanitasHandler: detach()
? 2025-10-18 15:12:06.619 D/BleConnector: BluetoothEvent received: Disconnected(deviceAddress=C7:34:11:85:8F:E0, reason=SUCCESS) for SBF77
+ 2025-10-18 15:12:06.619 I/BleConnector: Event: Disconnected from C7:34:11:85:8F:E0. Reason: SUCCESS
? 2025-10-18 15:12:06.620 D/BleConnector: Disconnected event: Releasing active communicator: GattScaleAdapter
? 2025-10-18 15:12:06.621 D/BleConnector: Disconnected event: Active communicator released and set to null.

```

I waited a minute after it asked to stand on before saving the log (no debug enabled on the BT device)

**Comment by oliexdev** [comment]
because you are using the DEBUG Bluetooth Handler which just dump the GATT Service.

**Comment by bsimmo** [comment]
Your warning says my measurements (weight etc aka privacy and not saved to the log).
I'm confused what you want..
Or what your debug mode is then. (And probably other thinking debug is debug mode giving all the information and it's just privacy of no measurements being recorded from your warning).

Anyway: You now have logs for debug enabled on BT device and debug not enabled on BT device.

I can't find any other logs, but willing to do anything else you need.

**Comment by oliexdev** [comment]
please try out the latest openScale beta version on GitHub --> https://github.com/oliexdev/openScale/releases/tag/beta-build and post again the log file if it's didn't work.

**Comment by bsimmo** [comment]
It now disabled the connection after it says to step on (BT icon gets a cross through it).

| Field | Value |
|---|---|
| Time | 2025-10-18 16:24:23.620 |
| Session ID | 199f7ec02c4 |
| App | openScale |
| Version | 3.0-beta (69) |
| Package | com.health.openscale.beta |
| Build Type | beta |
| Device | motorola motorola edge 50 pro |
| Android | 15 (API 35) |
| Build ID | V1UMS35H.10-67-7-2 |
| Build Time | 2025-10-18T15:09:15Z |
| Git SHA | 1ec45a3 |

```diff
+ 2025-10-18 16:24:23.616 I/openScaleLog: File logging preference updated to: true (was: false)
? 2025-10-18 16:24:23.620 D/openScaleLog: Initial markdown-diff headers written to: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs/openScale_current_log.txt
? 2025-10-18 16:24:23.621 D/openScaleLog: Initial markdown-diff headers written to: /storage/emulated/0/Android/data/com.health.openscale.beta/files/logs/openScale_current_log.txt
+ 2025-10-18 16:24:23.622 I/openScaleLog: File logging enabled during runtime – started fresh session log.
? 2025-10-18 16:24:34.670 D/BluetoothScreen: Launching Bluetooth scan via permissionsLauncher (permissions granted)
+ 2025-10-18 16:24:34.675 I/BluetoothScannerMgr: Starting device scan for 20000 ms.
+ 2025-10-18 16:24:43.851 I/UserSettingsRepository: Saving device snapshot: addr=C7:34:11:85:8F:E0, name=SBF77, uuids=1, hint=Beurer BF950
+ 2025-10-18 16:24:53.015 I/BluetoothScannerMgr: Stopping device scan. Triggered by timeout: false
? 2025-10-18 16:24:53.019 D/BluetoothScannerMgr: Scan stopped. Found devices: 11
? 2025-10-18 16:25:07.792 D/DatabaseRepository: Inserting user: Ben
? 2025-10-18 16:25:07.809 D/UserSettingsRepository: Setting current user ID to: 1
+ 2025-10-18 16:25:07.819 I/SharedViewModel: Selected user: 1
+ 2025-10-18 16:25:07.857 I/BluetoothFacade: User context updated -> Ben
? 2025-10-18 16:25:10.382 D/BluetoothTopBar: User clicked bluetooth icon connect → trying to connect to saved device SBF77
+ 2025-10-18 16:25:10.383 I/BleConnector: Attempting to connect to SBF77
? 2025-10-18 16:25:10.383 D/BleConnector: Switching to new device: Releasing active communicator: null
? 2025-10-18 16:25:10.384 D/BleConnector: Switching to new device: Active communicator released and set to null.
? 2025-10-18 16:25:10.384 D/ScaleHandlerFactory: createCommunicator: Searching for communicator for 'SBF77' (C7:34:11:85:8F:E0). Handler hint: 'Beurer BF950'
+ 2025-10-18 16:25:10.384 I/ScaleHandlerFactory: Modern handler 'Beurer BF950' supports 'SBF77'.
+ 2025-10-18 16:25:10.388 I/ScaleHandlerFactory: Modern communicator 'GattScaleAdapter' created for 'SBF77' with linkMode=CONNECT_GATT.
+ 2025-10-18 16:25:10.388 I/BleConnector: ActiveCommunicator successfully created: GattScaleAdapter. Starting observation job...
? 2025-10-18 16:25:10.389 D/BleConnector: Adapter isConnected: false for SBF77 (Status: CONNECTING)
+ 2025-10-18 16:25:10.389 I/BleConnector: Adapter no longer reports connected for SBF77. Current status: CONNECTING. Expecting Disconnected Event.
+ 2025-10-18 16:25:10.423 I/GattScaleAdapter: Found C7:34:11:85:8F:E0 → stop scan + connect
? 2025-10-18 16:25:11.819 D/GattScaleAdapter: Services discovered for C7:34:11:85:8F:E0
? 2025-10-18 16:25:11.821 D/StandardBeurerSanitasHandler: handleConnected(userId=1, height=111.0, age=18)
? 2025-10-18 16:25:11.820 D/StandardBeurerSanitasHandler: attach()
? 2025-10-18 16:25:11.823 D/StandardBeurerSanitasHandler: tryAutoConsent called for appUserId=1
? 2025-10-18 16:25:11.822 D/GattScaleAdapter: → set notify on chr=00002a9d-0000-1000-8000-00805f9b34fb svc=0000181d-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:11.907 D/StandardBeurerSanitasHandler: No known scale index found for appUserId=1, auto-consent cannot proceed
? 2025-10-18 16:25:11.907 D/StandardBeurerSanitasHandler: → UCP LIST_ALL_USERS
? 2025-10-18 16:25:11.907 D/StandardBeurerSanitasHandler: Scale connected: userId=1, name=Ben
? 2025-10-18 16:25:11.910 D/StandardBeurerSanitasHandler: Loaded consent=-1 for scaleIndex=-1
? 2025-10-18 16:25:11.910 D/StandardBeurerSanitasHandler: Setting custom user list notifications on service=0000ffff-0000-1000-8000-00805f9b34fb for chrUserList=00000001-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:11.911 D/StandardBeurerSanitasHandler: Writing activity level for userId=1 to chrActivity=00000004-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:11.911 D/StandardBeurerSanitasHandler: Writing initials for userId=1 to chrInitials=00000002-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:11.912 D/BleConnector: Adapter isConnected: true for SBF77 (Status: CONNECTING)
+ 2025-10-18 16:25:11.912 I/BleConnector: Successfully connected to SBF77 via adapter's isConnected flow.
? 2025-10-18 16:25:11.914 D/BleConnector: BluetoothEvent received: Connected(deviceName=SBF77, deviceAddress=C7:34:11:85:8F:E0) for SBF77
+ 2025-10-18 16:25:11.914 I/BleConnector: Event: Connected to SBF77 (C7:34:11:85:8F:E0)
? 2025-10-18 16:25:11.914 D/BleConnector: BluetoothEvent received: DeviceMessage(message=Please step barefoot on the scale, deviceAddress=C7:34:11:85:8F:E0) for SBF77
? 2025-10-18 16:25:11.915 D/BleConnector: Event: Message from SBF77: Please step barefoot on the scale
? 2025-10-18 16:25:12.472 D/GattScaleAdapter: ← notify state chr=00002a9d-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 16:25:12.597 D/GattScaleAdapter: → set notify on chr=00002a9c-0000-1000-8000-00805f9b34fb svc=0000181b-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:12.652 D/GattScaleAdapter: ← notify state chr=00002a9c-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 16:25:12.779 D/GattScaleAdapter: → set notify on chr=00002a99-0000-1000-8000-00805f9b34fb svc=0000181c-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:12.817 D/GattScaleAdapter: ← notify state chr=00002a99-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 16:25:12.943 D/GattScaleAdapter: → set notify on chr=00002a9f-0000-1000-8000-00805f9b34fb svc=0000181c-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:12.982 D/GattScaleAdapter: ← notify state chr=00002a9f-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 16:25:13.109 D/GattScaleAdapter: → set notify on chr=00002a19-0000-1000-8000-00805f9b34fb svc=0000180f-0000-1000-8000-00805f9b34fb
- 2025-10-18 16:25:13.114 E/GattScaleAdapter: BLE operation failed
java.lang.IllegalArgumentException: could not get CCC descriptor for characteristic 00002a19-0000-1000-8000-00805f9b34fb
	at com.welie.blessed.BluetoothPeripheral.setNotify(BluetoothPeripheral.kt:1138)
	at com.welie.blessed.BluetoothPeripheral.setNotify(BluetoothPeripheral.kt:1119)
	at com.welie.blessed.BluetoothPeripheral.startNotify(BluetoothPeripheral.kt:1093)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$transport$1$setNotifyOn$1.invokeSuspend(GattScaleAdapter.kt:237)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$transport$1$setNotifyOn$1.invoke(Unknown Source:8)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$transport$1$setNotifyOn$1.invoke(Unknown Source:2)
	at com.health.openscale.core.bluetooth.scales.GattScaleAdapter$1.invokeSuspend(GattScaleAdapter.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)

? 2025-10-18 16:25:13.206 D/GattScaleAdapter: → write to chr=00002a2b-0000-1000-8000-00805f9b34fb svc=00001805-0000-1000-8000-00805f9b34fb len=10 withResp=true payload=[E9 07 0A 12 10 19 0B 06 00 00]
? 2025-10-18 16:25:13.237 D/GattScaleAdapter: ← write response chr=00002a2b-0000-1000-8000-00805f9b34fb len=10 status=SUCCESS payload=[E9 07 0A 12 10 19 0B 06 00 00]
? 2025-10-18 16:25:13.265 D/GattScaleAdapter: → read from chr=00002a29-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:13.297 D/GattScaleAdapter: ← received data chr=00002a29-0000-1000-8000-00805f9b34fb len=13 status=SUCCESS payload=[48 61 6E 73 20 44 69 6E 73 6C 61 67 65]
? 2025-10-18 16:25:13.300 D/StandardBeurerSanitasHandler: Device info: Hans Dinslage
? 2025-10-18 16:25:13.326 D/GattScaleAdapter: → read from chr=00002a24-0000-1000-8000-00805f9b34fb svc=0000180a-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:13.357 D/GattScaleAdapter: ← received data chr=00002a24-0000-1000-8000-00805f9b34fb len=5 status=SUCCESS payload=[53 42 46 37 37]
? 2025-10-18 16:25:13.360 D/StandardBeurerSanitasHandler: Device info: SBF77
? 2025-10-18 16:25:13.386 D/GattScaleAdapter: → read from chr=00002a19-0000-1000-8000-00805f9b34fb svc=0000180f-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:13.417 D/GattScaleAdapter: ← received data chr=00002a19-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[58]
? 2025-10-18 16:25:13.419 D/StandardBeurerSanitasHandler: Battery level: 88%
? 2025-10-18 16:25:13.529 D/GattScaleAdapter: → write to chr=00002a9f-0000-1000-8000-00805f9b34fb svc=0000181c-0000-1000-8000-00805f9b34fb len=1 withResp=true payload=[04]
? 2025-10-18 16:25:13.567 D/GattScaleAdapter: ← write response chr=00002a9f-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[04]
? 2025-10-18 16:25:13.594 D/GattScaleAdapter: → set notify on chr=00000001-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb
? 2025-10-18 16:25:13.627 D/GattScaleAdapter: ← notify state chr=00000001-0000-1000-8000-00805f9b34fb status=SUCCESS
? 2025-10-18 16:25:13.838 D/GattScaleAdapter: → write to chr=00000001-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb len=1 withResp=true payload=[00]
? 2025-10-18 16:25:13.867 D/GattScaleAdapter: ← write response chr=00000001-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[00]
? 2025-10-18 16:25:13.881 D/GattScaleAdapter: ← received data chr=00000001-0000-1000-8000-00805f9b34fb len=12 status=SUCCESS payload=[00 01 43 41 54 B9 07 0A 1B A8 01 03]
? 2025-10-18 16:25:13.884 D/StandardBeurerSanitasHandler: UCP indication received with non-response opcode=0x0 data=[00 01 43 41 54 B9 07 0A 1B A8 01 03]
? 2025-10-18 16:25:13.896 D/GattScaleAdapter: ← received data chr=00000001-0000-1000-8000-00805f9b34fb len=12 status=SUCCESS payload=[00 02 42 45 4E B9 07 03 1E B1 00 03]
? 2025-10-18 16:25:13.898 D/StandardBeurerSanitasHandler: UCP indication received with non-response opcode=0x0 data=[00 02 42 45 4E B9 07 03 1E B1 00 03]
? 2025-10-18 16:25:13.901 D/GattScaleAdapter: ← received data chr=00000001-0000-1000-8000-00805f9b34fb len=12 status=SUCCESS payload=[00 03 42 20 20 B9 07 07 1E B0 00 02]
? 2025-10-18 16:25:13.903 D/StandardBeurerSanitasHandler: UCP indication received with non-response opcode=0x0 data=[00 03 42 20 20 B9 07 07 1E B0 00 02]
? 2025-10-18 16:25:13.906 D/GattScaleAdapter: ← received data chr=00000001-0000-1000-8000-00805f9b34fb len=12 status=SUCCESS payload=[00 04 43 20 20 B9 07 0A 1B A4 00 03]
? 2025-10-18 16:25:13.908 D/StandardBeurerSanitasHandler: UCP indication received with non-response opcode=0x0 data=[00 04 43 20 20 B9 07 0A 1B A4 00 03]
? 2025-10-18 16:25:13.910 D/GattScaleAdapter: ← received data chr=00000001-0000-1000-8000-00805f9b34fb len=12 status=SUCCESS payload=[00 05 42 42 20 B9 07 03 1E B1 00 02]
? 2025-10-18 16:25:13.911 D/StandardBeurerSanitasHandler: UCP indication received with non-response opcode=0x0 data=[00 05 42 42 20 B9 07 03 1E B1 00 02]
? 2025-10-18 16:25:13.913 D/GattScaleAdapter: ← received data chr=00000001-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[01]
? 2025-10-18 16:25:13.914 D/StandardBeurerSanitasHandler: UCP indication received with non-response opcode=0x1 data=[01]
? 2025-10-18 16:25:13.975 D/GattScaleAdapter: → write to chr=00000004-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb len=1 withResp=true payload=[01]
? 2025-10-18 16:25:14.002 D/GattScaleAdapter: ← write response chr=00000004-0000-1000-8000-00805f9b34fb len=1 status=SUCCESS payload=[01]
? 2025-10-18 16:25:14.110 D/GattScaleAdapter: → write to chr=00000002-0000-1000-8000-00805f9b34fb svc=0000ffff-0000-1000-8000-00805f9b34fb len=3 withResp=true payload=[42 45 4E]
? 2025-10-18 16:25:14.137 D/GattScaleAdapter: ← write response chr=00000002-0000-1000-8000-00805f9b34fb len=3 status=SUCCESS payload=[42 45 4E]

```

**Comment by oliexdev** [comment]
please try again the latest beta build.

**Comment by bsimmo** [comment]
It's working now.
It can now connect, ask for the user from the grabbed list, take the confirmation PIN and collect the data.
It has then updated live when I stand on it too.

Bugs
- it _doesn't_ bring the scales names when asking for the user (it did in old java V3 and in V2)
- The BT icon _always_ has the line through it and doesn't show any other the other state.

Something for another day 

Will keep testing over the next week.
