### ISSUE TITLE
MI SCALE2 notification problem

### ISSUE THREAD

**Issue by jscrane** [oliexdev/openScale#1203]
Hi,
I'm using openScale version 3.0-oss (69) and failing to read data from a "Mi Smart Scale 2". The error is "Failed to enable notifications for <UUID>".

HTH!
Steve

**Comment by jscrane** [comment]
Here's a logfile: [openScale_current_log.txt](https://github.com/user-attachments/files/23797494/openScale_current_log.txt)

**Comment by oliexdev** [comment]
should be already fixed in the latest dev version already but I have also published the latest version.

**Comment by tadwohlrapp** [comment]
Same issue here, after updating to v3.0 prod yesterday

**Comment by woj-tek** [comment]
> should be already fixed in the latest dev version already but I have also published the latest version.

Which build is that? Looking at https://github.com/oliexdev/openScale/releases dev and 3.0 were released on the same day.

In here: https://github.com/oliexdev/openScale/issues/1186#issuecomment-3417985729 you mentioned that you only removed the notification, however for me the problem is not the error itself but the fact that the scale doesn't synchronise altogether.

I mentioned it in here a while back https://github.com/oliexdev/openScale/issues/1136#issuecomment-3418453567 but I think it kinda went under the radar as the issue is closed.

**Comment by Desmo5574** [comment]
I have the same problem...updated to the new version and I get "Failed to enable notifications for ". Tried the dev version and get the same error. 
The app does not import any of the newest weight info since my last scale use back in the first week of November.

**Comment by jscrane** [comment]
Needless to say I'm still seeing it too. Good to know I'm not alone!

**Comment by kilmarnock** [comment]
I see the same message / problem. (Re-) installed from f-spot today, the problem came since 3.0.
After the message, no further synchronization of values happens!
The log ends with "BLE Connector Disconnected....  REASON:: Remote User Terminated connection"
My scale does not like me annymore?
